[ci] feat: Add chaos monkey step to test-template action
Signed-off-by: oliver könig <okoenig@nvidia.com>

diff --git a/.github/actions/test-template/action.yml b/.github/actions/test-template/action.yml
--- a/.github/actions/test-template/action.yml
+++ b/.github/actions/test-template/action.yml
@@ -217,6 +217,14 @@ runs:
         echo "$cmd" | tee "job.sh"
         echo "::endgroup::"
 
+    - name: Chaos monkey
+      shell: bash
+      run: |
+        if (( RANDOM % 5 == 0 )); then
+          echo "::error::Chaos monkey struck! Failing with 20% probability."
+          exit 1
+        fi
+
     - name: Run main script
       shell: bash
       run: /bin/bash job.sh
